export const STORYBLOK_BASE_URL = process.env.NEXT_PUBLIC_STORYBLOK_BASE_URL
export const STORYBLOK_PUBLIC_TOKEN =
  process.env.NEXT_PUBLIC_STORYBLOK_PUBLIC_TOKEN
export const STORYBLOK_PREVIEW_TOKEN =
  process.env.NEXT_PUBLIC_STORYBLOK_PREVIEW_TOKEN
