export const STORYBLOK_BASE_URL = process.env.NEXT_PUBLIC_STORYBLOK_BASE_URL
export const STORYBLOK_TOKEN =
  process.env.NEXT_PUBLIC_STORYBLOK_TOKEN

export const STORYBLOK_VERSION =
  process.env.NEXT_PUBLIC_STORYBLOK_VERSION
